### ISSUE TITLE
Rebuild & Bundling

### ISSUE THREAD

**Issue by Felli** [GreenMeteor/humhub-githum-theme#1]
Build a bundle of the following modules within the theme through [Enterprise](http://docs.humhub.org/ee-README.html) documentation.

- [ ] Rebuild to EE standards #3
- [ ] Ask module owner @githubjeka for some help with bundling the [Tracker](https://github.com/githubjeka/tracker-issues) module. #4
- [ ] Documentation on how to work both the [Gitter](https://github.com/GreenVolume/humhub-gitter-module) & [GitHub](https://github.com/GreenVolume/humhub-github-module) modules within the theme, or find better way of implementing. #2
